Bugfix for css tags that don't have rules attrib.
Dalimil/Web-Design-Pirate pull request #7
Opened 2018-05-11 08:02 UTC by christoshrousis

As per issue #6 , there was a stylesheet that didn't have this prop, so it was throwing an error.

2018-05-13 15:20 UTC, Dalimil requested changes
The problem is that the cssRules is sometimes missing - perhaps because it includes external css files that fail to load.

2018-05-13 15:20 UTC, Dalimil commented on main/src/contentScripts.js
> +        cssText: (x.hasOwnProperty('rules') && x.cssRules && x.cssRules.length) ? [].slice.call(x.cssRules).map(r => r.cssText).join(" \n") : null,
I believe that `'rules'` is not part of the official spec. That's only what Chrome uses internally I think. But this extension is also for Firefox.

2018-05-13 22:52 UTC, christoshrousis commented on main/src/contentScripts.js
> +        cssText: (x.hasOwnProperty('rules') && x.cssRules && x.cssRules.length) ? [].slice.call(x.cssRules).map(r => r.cssText).join(" \n") : null,
we can maybe try:

('href' in x)

2021-01-02 06:38 UTC, Dalimil commented
Already fixed in latest release.

2021-01-02 06:38 UTC, closed without merging